name: sudoku
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- ncurses=5.9=10
- openssl=1.0.2n=0
- pip=9.0.1=py36_1
- pulp=1.6.8=py36_0
- pyparsing=2.2.0=py36_0
- python=3.6.4=0
- readline=7.0=0
- setuptools=39.0.1=py36_0
- sqlite=3.20.1=2
- tk=8.6.7=0
- wheel=0.30.0=py36_2
- xz=5.2.3=0
- zlib=1.2.11=0
